FROM bitwalker/alpine-erlang:19.3

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=docker REPLACE_OS_VARS=true SHELL=/bin/sh
